### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [Wekkel/prj-rev-bwfs-dasmoto#7]
https://github.com/Wekkel/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L1-L20

There's a lot of repetition here.

Move shared styles into a single CSS rule with a more general selector, so that you don't have to repeat the style in every single CSS rule.

```css
* {
  font-family: Helvetica;
}
```
